// <auto-generated />
using System;
using MainApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MainApp.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20221211192054_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.11");

            modelBuilder.Entity("LabsDB.Entity.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Login = "123",
                            Password = "123"
                        });
                });

            modelBuilder.Entity("LabsDB.Entity.Lamp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Glows")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Lamp");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Glows = true,
                            RoomId = 1,
                            TimeStamp = new DateTime(2022, 12, 11, 22, 20, 54, 379, DateTimeKind.Local).AddTicks(6453)
                        },
                        new
                        {
                            Id = 2,
                            Glows = true,
                            RoomId = 1,
                            TimeStamp = new DateTime(2022, 12, 11, 22, 20, 54, 379, DateTimeKind.Local).AddTicks(6468)
                        },
                        new
                        {
                            Id = 3,
                            Glows = true,
                            RoomId = 2,
                            TimeStamp = new DateTime(2022, 12, 11, 22, 20, 54, 379, DateTimeKind.Local).AddTicks(6470)
                        },
                        new
                        {
                            Id = 4,
                            Glows = false,
                            RoomId = 2,
                            TimeStamp = new DateTime(2022, 12, 11, 22, 20, 54, 379, DateTimeKind.Local).AddTicks(6471)
                        });
                });

            modelBuilder.Entity("LabsDB.Entity.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Room");

                    b.HasData(
                        new
                        {
                            Id = 1
                        },
                        new
                        {
                            Id = 2
                        });
                });

            modelBuilder.Entity("LabsDB.Entity.Lamp", b =>
                {
                    b.HasOne("LabsDB.Entity.Room", "Room")
                        .WithMany("Lamps")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("LabsDB.Entity.Room", b =>
                {
                    b.Navigation("Lamps");
                });
#pragma warning restore 612, 618
        }
    }
}
